// Kiến thức Hóa 9 — trích từ "Sổ Tay Kiến Thức Hóa Học Cấp 2 (Lớp 9)"
// Nguồn: kien_thuc_hoa_9 (1).pdf — giữ nguyên thuật ngữ/nội dung cốt lõi của tài liệu.
export const K9PDF = [
['Khối lượng mol (M)','Hóa 9 · Công thức cơ bản','M = m / n (g/mol)','Biết m và n → tính M.','m: khối lượng (g); n: số mol.'],
['Thể tích khí ở đkc','Hóa 9 · Công thức cơ bản','V = 24,79 × n (Lít)','V khí = 24,79n ở đkc.','Tài liệu quy ước đkc: 25°C và 1 bar.'],
['Số mol theo số hạt','Hóa 9 · Công thức cơ bản','n = N / Nₐ (mol)','Số hạt → chia Nₐ để ra mol.','Nₐ = 6,022 × 10²³; N là số phân tử/nguyên tử.'],
['Nồng độ mol (Cₘ)','Hóa 9 · Công thức cơ bản','Cₘ = n / V (mol/L)','Mol chia thể tích dung dịch (L).','Đơn vị M hoặc mol/L.'],
['Nồng độ phần trăm (C%)','Hóa 9 · Công thức cơ bản','C% = (mct / mdd) × 100%','Chất tan / dung dịch × 100%.','mct = C%×mdd/100%; mdd = mct×100%/C%.'],
['Khối lượng riêng (D)','Hóa 9 · Công thức cơ bản','D = m / V (g/mL hoặc g/cm³)','Khối lượng chia thể tích.','Đổi đơn vị khối lượng và thể tích cho đồng nhất.'],
['Độ tan (S)','Hóa 9 · Công thức cơ bản','S = (mct / mₙước) × 100 (g/100g nước)','Luôn quy về 100 g nước.','mct là khối lượng chất tan; mₙước là khối lượng nước.'],
['Tỉ khối hơi của khí','Hóa 9 · Công thức cơ bản','dA/B = M_A / M_B; dA/kk = M_A / 29','So M để so tỉ khối.','Với hỗn hợp: Mhh = (M₁n₁ + M₂n₂ + …)/(n₁+n₂+…).'],
['Acid','Hóa 9 · Hợp chất vô cơ','Nguyên tử H liên kết với gốc acid.','Nhớ: acid thường có H ở đầu công thức.','Ví dụ trong tài liệu: HCl, H₂SO₄, HNO₃, H₃PO₄, H₂CO₃, CH₃COOH, H₂S.'],
['Base (Hydroxide)','Hóa 9 · Hợp chất vô cơ','Nguyên tử kim loại liên kết với một hay nhiều nhóm (−OH).','Kim loại + OH → hydroxide/base.','Ví dụ: NaOH, Ba(OH)₂, Ca(OH)₂, Mg(OH)₂, Fe(OH)₂, Fe(OH)₃, Al(OH)₃.'],
['Oxide kim loại','Hóa 9 · Hợp chất vô cơ','Oxide tạo từ kim loại + O₂; thường là oxide base.','Kim loại + O₂ → oxide kim loại.','Ví dụ: Na₂O, CaO, Fe₂O₃; oxide base: Na₂O, CaO, MgO, CuO.'],
['Oxide phi kim','Hóa 9 · Hợp chất vô cơ','Oxide tạo từ phi kim + O₂; thường là oxide acid.','Phi kim + O₂ → oxide phi kim.','Ví dụ: CO₂, SO₂, SO₃, P₂O₅, CO, NO.'],
['Oxide lưỡng tính','Hóa 9 · Hợp chất vô cơ','Có thể tác dụng với cả acid và base.','Lưỡng tính → gặp acid hoặc base đều có thể phản ứng.','Ví dụ: Al₂O₃, ZnO.'],
['Oxide trung tính','Hóa 9 · Hợp chất vô cơ','Hầu như không tác dụng với acid, base, nước ở điều kiện thường và không tạo muối.','Trung tính → rất ít phản ứng acid/base/nước.','Ví dụ: CO, NO, N₂O.'],
['Muối','Hóa 9 · Hợp chất vô cơ','Kim loại liên kết với gốc acid.','Kim loại + gốc acid → muối.','Ví dụ: NaCl, AgNO₃, KCl, MgCl₂.'],
['Phản ứng trung hòa','Hóa 9 · Phản ứng vô cơ','Base + Acid → Muối + Nước','Gặp acid + base → nghĩ ngay trung hòa.','Ví dụ: Ca(OH)₂ + H₂SO₄ → CaSO₄ + 2H₂O.'],
['Kim loại + O₂','Hóa 9 · Phản ứng vô cơ','Kim loại + O₂ → Oxide kim loại (oxide base)','Kim loại cháy trong oxygen → oxide.','Ví dụ: 2Ba + O₂ → 2BaO.'],
['Phi kim + O₂','Hóa 9 · Phản ứng vô cơ','Phi kim + O₂ → Oxide phi kim (oxide acid)','Phi kim + oxygen → oxide phi kim.','Ví dụ: C + O₂ → CO₂.'],
['Oxide acid + Base','Hóa 9 · Phản ứng vô cơ','Oxide acid + Base → Muối + Nước','CO₂/SO₂ + base → muối + nước.','Ví dụ: Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O.'],
['Oxide base + Acid','Hóa 9 · Phản ứng vô cơ','Oxide base + Acid → Muối + Nước','Oxide base gặp acid → muối + nước.','Ví dụ: Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O.'],
['Oxide base + Oxide acid','Hóa 9 · Phản ứng vô cơ','Oxide base + Oxide acid → Muối','Hai oxide trái tính → muối.','Ví dụ: CaO + CO₂ → CaCO₃.'],
['Oxide acid + H₂O','Hóa 9 · Phản ứng vô cơ','Oxide acid + H₂O → Acid','Oxide acid + nước → acid.','Ví dụ: SO₃ + H₂O → H₂SO₄.'],
['Oxide base + H₂O','Hóa 9 · Phản ứng vô cơ','Oxide base + H₂O → Base; áp dụng với base tan: Na, K, Ba, Ca.','Oxide base tan + nước → hydroxide.','Ví dụ: Na₂O + H₂O → 2NaOH.'],
['Nhiệt phân base không tan','Hóa 9 · Phản ứng vô cơ','Base không tan —t°→ Oxide base + H₂O','Base không tan gặp nhiệt → oxide + nước.','Ví dụ: Cu(OH)₂ —t°→ CuO + H₂O.'],
['Muối + Kim loại','Hóa 9 · Phản ứng vô cơ','Muối + Kim loại → Muối mới + Kim loại mới','Kim loại mạnh hơn có thể đẩy kim loại yếu hơn khỏi muối.','Ví dụ: Zn + FeSO₄ → ZnSO₄ + Fe.'],
['Muối + Acid','Hóa 9 · Phản ứng vô cơ','Muối + Acid → Muối mới + Acid mới khi sản phẩm có khí, kết tủa hoặc chất ít tan.','Tìm khí/kết tủa/ít tan để quyết định phản ứng.','Muối chứa CO₃²⁻ hoặc HCO₃⁻ + acid → muối mới + CO₂↑ + H₂O.'],
['Muối + Base','Hóa 9 · Phản ứng vô cơ','Muối + Base → Muối mới + Base mới khi có khí, kết tủa hoặc chất ít tan.','Tìm chất tạo khí/kết tủa/ít tan.','Ví dụ: FeSO₄ + 2NaOH → Fe(OH)₂↓ + Na₂SO₄.'],
['Muối + Muối','Hóa 9 · Phản ứng vô cơ','Muối + Muối → 2 Muối mới','Phản ứng trao đổi khi tạo sản phẩm phù hợp.','Ví dụ: 2AgNO₃ + BaCl₂ → 2AgCl↓ + Ba(NO₃)₂.'],
['Kim loại + Phi kim','Hóa 9 · Phản ứng vô cơ','Kim loại + Phi kim (trừ O₂) → Muối','Kim loại kết hợp phi kim → muối.','Ví dụ: 2Na + Cl₂ → 2NaCl.'],
['Điện phân muối nóng chảy','Hóa 9 · Phản ứng vô cơ','Muối —điện phân→ Kim loại + Phi kim','Điện phân nóng chảy có thể tạo kim loại và phi kim.','Ví dụ: 2NaCl —đpnc→ 2Na + Cl₂↑.'],
['Định luật bảo toàn khối lượng','Hóa 9 · Đại lượng & định luật','Trong phản ứng hóa học, tổng khối lượng chất tham gia bằng tổng khối lượng sản phẩm.','m chất tham gia = m chất sản phẩm.','Ví dụ: mBaCl₂ + mNa₂SO₄ = mBaSO₄ + mNaCl (theo tài liệu).'],
['Tính chất kim loại','Hóa 9 · Kim loại & phi kim','Kim loại có tính dẻo, dẫn điện, dẫn nhiệt, ánh kim và có xu hướng nhường electron.','Kim loại → thường nhường e.','Tài liệu nêu: Au dẻo nhất; Ag dẫn điện/nhiệt tốt; Hg nóng chảy thấp; W cao; Li nhẹ; Os nặng; Cr cứng.'],
['Tính chất phi kim','Hóa 9 · Kim loại & phi kim','Phi kim thường không có ánh kim, dẫn điện/nhiệt kém (trừ than chì), có thể rắn/lỏng/khí và thường nhận electron.','Phi kim → thường nhận e.','Phi kim rắn thường giòn; khối lượng riêng thường nhỏ hơn kim loại.'],
['Dãy hoạt động hóa học của kim loại','Hóa 9 · Dãy hoạt động','K Na Ba Ca Mg Al Zn Fe Ni Sn Pb (H) Cu Hg Ag Pt Au','Đi từ trái sang phải: hoạt động hóa học giảm dần.','Mẹo trong tài liệu: “Khi nào bạn cần may áo giáp sắt nhớ sang phố hỏi cửa hàng Á phi Âu”.'],
['Kim loại mạnh + H₂O','Hóa 9 · Dãy hoạt động','K, Na, Ba, Ca tác dụng với H₂O ở điều kiện thường tạo hydroxide (base) và H₂.','Kim loại mạnh + nước → base + H₂.','Theo tài liệu, đây là nhóm kim loại mạnh.'],
['Kim loại trung bình + Acid loãng','Hóa 9 · Dãy hoạt động','Mg → Pb tác dụng với acid giải phóng H₂; không tác dụng với nước lạnh, chỉ tác dụng với hơi nước ở nhiệt độ cao.','Đứng trước H → có thể giải phóng H₂ với acid loãng.','Áp dụng theo điều kiện tài liệu nêu.'],
['Kim loại yếu + Acid loãng','Hóa 9 · Dãy hoạt động','Cu → Au không tác dụng với dung dịch HCl, H₂SO₄ loãng để giải phóng H₂.','Sau H → không đẩy H₂ khỏi acid loãng.','Không suy ra mọi acid đều không phản ứng; tài liệu chỉ nêu acid loãng này.'],
['Phản ứng thế kim loại','Hóa 9 · Dãy hoạt động','Kim loại đứng trước đẩy kim loại đứng sau ra khỏi dung dịch muối của nó, trừ K, Na, Ba, Ca,...','Đứng trước → có khả năng đẩy đứng sau.','K, Na, Ba, Ca tan trong nước nên không xét theo cách thông thường trong dung dịch.'],
['Kim loại + O₂ / phi kim / acid','Hóa 9 · Kim loại & phi kim','Kim loại + O₂ → oxide (trừ Au, Ag, Pt); kim loại + phi kim → muối; kim loại mạnh + H₂O → base + H₂.','Nhớ 3 đường phản ứng cơ bản của kim loại.','Kim loại trung bình + H₂O ở nhiệt độ cao → oxide + H₂; kim loại mạnh/trung bình + acid loãng → muối + H₂.']
];

export const R9PDF = [
['Ca(OH)₂ + H₂SO₄','Ca(OH)₂ + H₂SO₄ → CaSO₄ + 2H₂O','Base + acid → muối + nước.'],
['2Ba + O₂','2Ba + O₂ → 2BaO','Kim loại + O₂ → oxide kim loại.'],
['C + O₂','C + O₂ → CO₂','Phi kim + O₂ → oxide phi kim.'],
['Ca(OH)₂ + CO₂','Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O','Oxide acid + base → muối + nước.'],
['Fe₂O₃ + HCl','Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O','Oxide base + acid → muối + nước.'],
['CaO + CO₂','CaO + CO₂ → CaCO₃','Oxide base + oxide acid → muối.'],
['SO₃ + H₂O','SO₃ + H₂O → H₂SO₄','Oxide acid + nước → acid.'],
['Na₂O + H₂O','Na₂O + H₂O → 2NaOH','Oxide base + nước → base với Na, K, Ba, Ca theo tài liệu.'],
['Cu(OH)₂ —t°→','Cu(OH)₂ —t°→ CuO + H₂O','Base không tan bị nhiệt phân hủy.'],
['Zn + FeSO₄','Zn + FeSO₄ → ZnSO₄ + Fe','Muối + kim loại → muối mới + kim loại mới.'],
['BaCl₂ + H₂SO₄','BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl','Muối + acid; tạo kết tủa nên phản ứng xảy ra.'],
['CaCO₃ + HCl','CaCO₃ + 2HCl → CaCl₂ + CO₂↑ + H₂O','Carbonate gặp acid → CO₂↑ + H₂O + muối mới.'],
['FeSO₄ + NaOH','FeSO₄ + 2NaOH → Fe(OH)₂↓ + Na₂SO₄','Muối + base; tạo kết tủa.'],
['AgNO₃ + BaCl₂','2AgNO₃ + BaCl₂ → 2AgCl↓ + Ba(NO₃)₂','Muối + muối; tạo AgCl kết tủa.'],
['Na + Cl₂','2Na + Cl₂ → 2NaCl','Kim loại + phi kim → muối.'],
['Điện phân NaCl nóng chảy','2NaCl —đpnc→ 2Na + Cl₂↑','Điện phân muối nóng chảy → kim loại + phi kim.'],
];

export const F9PDF = [
['Khối lượng mol','M = m / n','g/mol'],
['Thể tích khí ở đkc','V = 24,79 × n','L; đkc theo tài liệu: 25°C, 1 bar'],
['Số mol theo số hạt','n = N / Nₐ','Nₐ = 6,022 × 10²³'],
['Nồng độ mol','Cₘ = n / V','mol/L hoặc M'],
['Nồng độ phần trăm','C% = (mct / mdd) × 100%','mct: chất tan; mdd: dung dịch'],
['Khối lượng riêng','D = m / V','g/mL hoặc g/cm³'],
['Độ tan','S = (mct / mₙước) × 100','g/100g nước'],
['Tỉ khối khí','dA/B = MA / MB','dA/kk = MA / 29'],
['Khối lượng mol hỗn hợp','Mhh = (M₁n₁ + M₂n₂ + …)/(n₁+n₂+…)','Dùng khi có nhiều khí'],
['Bảo toàn khối lượng','mchất tham gia = mchất sản phẩm','Tổng khối lượng trước = sau phản ứng']
];
